### PR TITLE
Feat : Add entity linker

### LINKED ISSUE #20: Feat : Implement the Entity Linker
The Entity Linker should:
- without any parameters other than the KG, build a minimum Entity linker based on string matching.
- Apply the components in the right order (Matcher then Disambiguator)

The goal is to make the Entity Linkeker a spaCy pipe.

Attributes:
- kg: KnowledgeGraph
- spacy_model : spacy.Language
- entity_matcher: EntityMatcher, optional
- disambiguator: Disambiguator, optional

Methods:

- __call__(spacy.Doc): spacy.Doc

### PR DESCRIPTION
**Pull request by schmarion**

### CODE REVIEW

**Review by msesboue — COMMENTED** [review]
It looks pretty good to me.

There is only one thing that I am thinking of, but I do not know how to handle it, and if we should handle it right now. 
The way the entity matcher and linker are implemented so far does not let us define different way of handling different matching kind. But last time I suggest to remove the string matching if we have the fuzzy one. It might be a mistake. I don't know. Maybe we can discuss it a bit. But I don't think it worth spending a lot of time on it.

**Comment by schmarion** [comment]
Yes, I have the same concern. 
I thought we could have a list for `spans_key` instead of a string and override the has_overlap method. We'd also need to make some changes in `remove_ambiguities` and `extract_overlapping_spans`.
Not sure it is the best thing to do but it could work.

**Comment by msesboue** [comment]
Ok, so I suggest we take 30 minutes to discuss what it will imply to make changes when needed, and we create an issue.

In the meantime, we complete this MR with the current design. What do you think?

**Comment by schmarion** [comment]
Yes great

**Review by msesboue — APPROVED** [review]

**Pull request merged**
